name: Build Docker with dev-dependencies

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set git to use CRLF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol crlf

      - run: git config --global user.name 'GitHub'
      - run: git config --global user.email 'info@symbiosika.de'

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.BE_GH_REGISTRY_KEY }}
          ref: main
          submodules: recursive
          fetch-depth: 2

      - name: Log submodule status
        run: |
          echo "Main repository status:"
          git status
          echo "\nSubmodule commits:"
          git submodule foreach 'echo "Repository: $name"; git log -1 --oneline; echo "Status:"; git status --short; echo "----------------"'

      # - name: Download artifact "kinaut_robot-frontend"
      #   uses: bettermarks/action-artifact-download@0.5.1
      #   with:
      #     repo: symbiosika/kinaut_robot-frontend
      #     token: ${{ secrets.BE_GH_REGISTRY_KEY }}
      #     artifact_name: kinaut_robot-frontend-develop
      #     wait_seconds: 1

      - name: Download artifact "kinaut_login"
        uses: bettermarks/action-artifact-download@0.5.1
        with:
          repo: symbiosika/kinaut_login
          token: ${{ secrets.BE_GH_REGISTRY_KEY }}
          artifact_name: kinaut_login-main
          wait_seconds: 1

      - name: Download artifact "kinaut_robot-base"
        uses: bettermarks/action-artifact-download@0.5.1
        with:
          repo: symbiosika/kinaut_robot-base
          token: ${{ secrets.BE_GH_REGISTRY_KEY }}
          artifact_name: kinaut_robot-base-develop
          wait_seconds: 1

      # - name: Download artifact "docs-suite"
      #   uses: bettermarks/action-artifact-download@0.5.1
      #   with:
      #     repo: symbiosika/kinaut_docs
      #     token: ${{ secrets.BE_GH_REGISTRY_KEY }}
      #     artifact_name: kinaut_docs
      #     wait_seconds: 1

      - name: unzip all Artifacts
        run: |
          mkdir tmp_docs
          mkdir -p dist/static
          mkdir -p dist/static/docs
          mkdir -p dist/public
          unzip -o kinaut_robot-frontend-develop -d ./dist
          unzip -o kinaut_login-main -d ./dist/public
          unzip -o kinaut_robot-base-develop -d ./dist
          # unzip -okinaut_docs -d ./tmp_docs
          # cp -r tmp_docs/* dist/static/docs/
          # echo "debug"
          ls -a

      - name: Build Docker image
        run: |
          docker build --target release-ci -t kinaut_robot-develop .

      - name: Tag Docker image
        run: |
          docker tag kinaut_robot-develop ghcr.io/symbiosika/kinaut_robot-develop:1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.BE_GH_REGISTRY_KEY }}

      - name: Push Docker image
        run: |
          docker push ghcr.io/symbiosika/kinaut_robot-develop:1

      # - name: Trigger Coolify Deployment
      #   run: |
      #     curl -X POST "${{ secrets.COOLIFY_DEPLOY_SERVER_1 }}/api/v1/deploy?uuid=${{ secrets.COOLIFY_PROJECT_ID_DEV_SYMBIOSIKA_DE }}&force=false" \
      #     -H "Authorization: Bearer ${{ secrets.COOLIFY_DEPLOY_BEARER_SERVER_1 }}" \
      #     -H "Content-Type: application/json"
